version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    depends_on:
      - postgres
    env_file: .env
    command: npm start
    ports:
      - 3000:3000
    restart: on-failure
    networks:
      - net

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres:/data/postgres
    env_file: .env
    ports:
      - 5432:5432
    restart: on-failure
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  postgres:
